// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGTMqJaRgw-7817m3trPGc26EqxKedMds',
    appId: '1:856367310343:web:78197930adb73422a1eca2',
    messagingSenderId: '856367310343',
    projectId: 'personal-app-6c704',
    authDomain: 'personal-app-6c704.firebaseapp.com',
    storageBucket: 'personal-app-6c704.firebasestorage.app',
    measurementId: 'G-MBHHSXV140',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4eMqOixhLSwC9scUWWlBbYNyxXSHm5_c',
    appId: '1:856367310343:android:67e38ae8a27d363fa1eca2',
    messagingSenderId: '856367310343',
    projectId: 'personal-app-6c704',
    storageBucket: 'personal-app-6c704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiSQlf0ZnzJmI05NqCsi_PA5XNy8pbo5c',
    appId: '1:856367310343:ios:10daf0b013d7980ea1eca2',
    messagingSenderId: '856367310343',
    projectId: 'personal-app-6c704',
    storageBucket: 'personal-app-6c704.firebasestorage.app',
    iosClientId: '856367310343-k2lqagbndmdmerqi3ifmorq3lknnu6ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.quinez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiSQlf0ZnzJmI05NqCsi_PA5XNy8pbo5c',
    appId: '1:856367310343:ios:10daf0b013d7980ea1eca2',
    messagingSenderId: '856367310343',
    projectId: 'personal-app-6c704',
    storageBucket: 'personal-app-6c704.firebasestorage.app',
    iosClientId: '856367310343-k2lqagbndmdmerqi3ifmorq3lknnu6ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.quinez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGTMqJaRgw-7817m3trPGc26EqxKedMds',
    appId: '1:856367310343:web:223e33fc60a37b69a1eca2',
    messagingSenderId: '856367310343',
    projectId: 'personal-app-6c704',
    authDomain: 'personal-app-6c704.firebaseapp.com',
    storageBucket: 'personal-app-6c704.firebasestorage.app',
    measurementId: 'G-YRK92WGE9P',
  );
}
